name: 'On push'
on:
  push:
    branches:
      - 'master'
    tags:
      - '!**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: setup node
        with:
          node-version: '14.x'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cache-

      - run: |
          git config --global user.email "cakeinpanic@gmail.com"
          git config --global user.name "Katya Bot"

      - name: 'install'
        run: npm i

      - name: 'build'
        run: npm run build

      - uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo
          # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Destination branch to push changes
          branch: pages
          # Use force push to fully overwrite the destination branch
          force: true
          # We have to push from the folder where files were generated.
          # Same were the new repo was initialized in the previous step
          directory: docs


